# -*- coding: utf-8 -*-
"""Encoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1akk16RCcobU0WbYlXctkscCWrVvum2q3
"""

from sklearn.preprocessing import LabelEncoder

labels = ["cat", "dog", "fish", "dog", "cat"]
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

print("Encoded Labels:", encoded_labels)

print("Inverse Transform (Original Labels):", label_encoder.inverse_transform(encoded_labels))

from sklearn.preprocessing import OneHotEncoder

categories = [["cat"], ["dog"], ["fish"], ["dog"], ["cat"]]

onehot_encoder = OneHotEncoder(sparse_output=False)

encoded_features = onehot_encoder.fit_transform(categories)

print("Encoded Features (One-Hot):")
print(encoded_features)

print("\nCategories:", onehot_encoder.categories_)

original_categories = onehot_encoder.inverse_transform(encoded_features)
print("\nInverse Transformed Categories:")
print(original_categories)